---
- name: install nginx
  tasks:
    - name: install nginx
      become: True
      yum: name=nginx state=latest update_cache=yes

    - name: create nginx bare-bones config for redirection
      become: True
      template: src=nginx_sites_default.j2 dest=/etc/nginx/sites-enabled/default
      notify: restart nginx
    - meta: flush_handlers
    - name: start nginx
      become: True
      service: name=nginx state=started enabled=yes
